### ISSUE TITLE
Send-xmlrpcrequest params always passing a string

### ISSUE THREAD

**Issue by allywilson** [lipkau/XmlRpc#2]
I'm trying to interact with the Spacewalk (aka Redhat Satellite 5) API using your module.

I can login fine, I can retrieve a list of systems, but then if I try to get information regarding 1 particular system it fails.

The reason it seems is that Send-XmlRpcRequest will always send Params as strings, and the xmlrpc API expects 1 of those params to be an integer. 

Example code:

```
$spacewalkServer = "192.168.0.3"
$spacewalkURL = "http://$spacewalkServer/rpc/api/"
$loginSession = Send-XmlRpcRequest -Url $spacewalkURL -MethodName "auth.login" -Params @('admin', 'password')
$key = $loginSession.methodResponse.params.param.value.string
Send-XmlRpcRequest -Url $spacewalkURL -MethodName "system.get_dmi" -Params @($key,1000010001)

```
Output:

> com.redhat.rhn.common.translation.TranslationException: Could not find translator for class java.lang.String to class java.lang.Integer

I can get Python to send that 1 value as an integer, just not this unfortunately.

Any thoughts?

**Comment by lipkau** [comment]
can you show me the xml payload you send with python?

This module should format integers properly:
https://github.com/lipkau/XmlRpc/blob/41885fe1061f41acf7bfd2d9c512887e73502bde//XmlRpc.psm1#L80-L83

you can see the xml payload the module generated by using the `-debug` switch. this is the message you can use for entering suspend mode:
https://github.com/lipkau/XmlRpc/blob/41885fe1061f41acf7bfd2d9c512887e73502bde/XmlRpc.psm1#L313

**Comment by allywilson** [comment]
Here's the Python (v2) code that works:

```
#!/usr/bin/env python
import xmlrpclib

SATELLITE_HOST = "192.168.0.3"
SATELLITE_URL = "http://%s/rpc/api" % SATELLITE_HOST
login = "admin"
password = "password"

client = xmlrpclib.Server(SATELLITE_URL, verbose=0)
key = client.auth.login(login, password)
print client.system.get_dmi(key,1000010001)
```
I'll see if I can capture the payload and get back to you.

**Comment by allywilson** [comment]
Here's the payloads:

Python Payload:

```
<?xml version='1.0'?>
<methodCall>
<methodName>system.get_dmi</methodName>
<params>
<param>
<value><string>42xdf9cc0ef75c84938c32be7932474fc15e93182ab7300f731bff3097036a1e755</string></value>
</param>
<param>
<value><int>1000010000</int></value>
</param>
</params>
</methodCall>
```


Powershell Payload:

```
<?xml version="1.0"?>
<methodCall>
<methodName>system.get_dmi</methodName>
<params>
<param>
<value><String>36xeaa170e829a2ae47ff8ae3ce3dd991db8c98e42ecd16ac8b7397056e1229f283</String></value>
</param>
<param>
<value><Int32>1000010000</Int32></value>
</param>
</params>
</methodCall>

```

Only difference I can see is `<int>` vs `<int32>` - are they both supposed to be valid for xmlrpc implementations?

**Comment by lipkau** [comment]
one difference in there is: the server I developed this for required integers to be defined as `<int32>`.
Yours wants `<int>`.

As far as I can tell, there is no way for the module to be smart enough to decide which one of those to use.
But here is something you can try:
replace this code snipe of `XmlRpc.psm1` (line 79 to 83)
https://github.com/lipkau/XmlRpc/blob/41885fe1061f41acf7bfd2d9c512887e73502bde/XmlRpc.psm1#L79-L83

with this:

```powershell
        # Return simple Types
        if (('Double','Boolean','False') -contains $Type)
        {
            return "<value><$($Type)>$($inputObject)</$($Type)></value>"
        }

        # Return Integers
        if ('Int32' -eq$Type)
        {
            return "<value><int>$($inputObject)</int></value>"
        }
```

**Comment by lipkau** [comment]
Or.... if you are dealing with a number that not to larger, you can leverage this part of the function:
https://github.com/lipkau/XmlRpc/blob/41885fe1061f41acf7bfd2d9c512887e73502bde/XmlRpc.psm1#L92-L95

by using it as:
```powershell
Send-XmlRpcRequest -Url $spacewalkURL -MethodName "system.get_dmi" -Params @($key,[int16](1000010001))
```

_edit: which after testing... is to large for int16_

**Comment by allywilson** [comment]
After modifying lines 79 to 83 in your first suggestion it's working perfectly, thank you!
